version: "3.7"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - core
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    command: npm run start

  core:
    container_name: pipeline
    image: ghcr.io/julianfrattini/cira:0.9.6
    ports:
      - "8000:8000"

networks:
  cira:
    driver: bridge