version: "3.7"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - base
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    command: npm run start

  base:
    container_name: ghcr.io/julianfrattini/cira:0.9.2
    build: .
    ports:
      - "8000:8000"

networks:
  cira:
    driver: bridge